### ISSUE TITLE
大佬，能分享一下你是怎么把其他支付平台聚合在一起的吗？

### ISSUE THREAD

**Issue by Adaclass** [dengyuhan/SmartPay#1]

**Comment by xiandanin** [comment]
每个平台的调用方式、参数、结果都不一样，所以自定义了接口来统一它们，[SmartPayCall](https://github.com/dengyuhan/SmartPay/blob/master/smartpay/src/main/java/com/dyhdyh/smartpay/SmartPayCall.java)就是处理调起平台的接口，[SmartPayCallAdapter](https://github.com/dengyuhan/SmartPay/blob/master/smartpay/src/main/java/com/dyhdyh/smartpay/SmartPayCallAdapter.java)再根据[PayType](https://github.com/dengyuhan/SmartPay/blob/master/smartpay/src/main/java/com/dyhdyh/smartpay/PayType.java)来决定实例化哪个`SmartPayCall`，为了让参数统一所以`SmartPayCall`接收到的参数是Map，在平台的具体实现中再把参数加工成平台需要的格式（参考[WeChatPayBaseCall](https://github.com/dengyuhan/SmartPay/blob/master/smartpay/src/main/java/com/dyhdyh/smartpay/wechat/WeChatPayBaseCall.java)），把平台返回的结果统一用Map接收，再定义一个转换器[SmartPayResultConverter](https://github.com/dengyuhan/SmartPay/blob/master/smartpay/src/main/java/com/dyhdyh/smartpay/SmartPayResultConverter.java)封装成自己要的格式

**Comment by Adaclass** [comment]
大佬666
